name: Build binaries
on: pull_request
jobs:
  binary:
    name: Build binary
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.2'
      - name: Build Binary
        run: |
          go build .
